### ISSUE TITLE
这个typescript-guide 和TypeScript Language Specification什么关系？

### ISSUE THREAD

**Issue by bugknightyyp** [vilic/typescript-guide#5]
你是想写本关于 typescript 指南的书吗？

**Comment by vilicvane** [comment]
囧, 不算书, 就是一个快速上手的手册. 和 lang spec 差异肯定很大, lang spec 一般不是给人学习用的, 里面记录的都是语言细节, 非常详尽, 但也难以阅读. 更像 http://www.typescriptlang.org/Handbook
